### ISSUE TITLE
Scripts không thể chặn gợi ý

### ISSUE THREAD

**Issue by zzeuss007** [nmtrung/greasemonkey-scripts#7]
Sao scripts không chặn được gợi ý vậy bạn?
![Untitled](https://user-images.githubusercontent.com/82309119/118483004-b1476180-b73f-11eb-913f-8a75c3e54d02.png)

**Comment by nmtrung** [comment]
bỏ không phát triển nữa bạn ơi.
Có cái này thay thế rồi, đã dùng, rất ngon
https://www.fbpurity.com/install.htm

**Comment by zzeuss007** [comment]
Ngon nhưng hơi bất tiện bạn ,phải đổi sang ngôn ngữ US

**Comment by zzeuss007** [comment]
mình close issue đây
